### ISSUE TITLE
Stream of Users

### ISSUE THREAD

**Issue by Cm-8** [bitfinexcom/bfx-ost-streamer#8]
Hi to all,

Can this plugin be used to send user data from third-party apps to the osTicket address book? 
Or to acquire data from third parties based on the user who opened the ticket?

Thanks

**Comment by davide-scola** [comment]
hello @Cm-8,

> Can this plugin be used to send user data from third-party apps to the osTicket address book?

unfortunately no, as this plugin works the other way around

> Or to acquire data from third parties based on the user who opened the ticket?

this plugin could be used to produce a stream of newly created users on [osTicket](https://osticket.com/), so that the consumer can get the additional information from the third-party system; however, this is not the main purpose of this plugin and seems like overkill

I close this issue for now, please let me know if you need further information
